export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_TO_CART_USER = 'ADD_TO_CART_USER';
export const GET_CART_ITEMS_USER = 'GET_CART_ITEMS_USER';
export const REMOVE_CART_ITEM_USER = 'REMOVE_CART_ITEM_USER';
export const ON_SUCCESS_BUY_USER = 'ON_SUCCESS_BUY_USER';

export const UPDATE_DATA_USER = 'UPDATE_DATA_USER';
export const CLEAR_UPDATE_DATA_USER = 'CLEAR_UPDATE_DATA_USER';

export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';

export const GET_BRANDS = 'GET_BRANDS';
export const ADD_BRAND = 'ADD_BRAND';

export const GET_WOODS = 'GET_WOODS';
export const ADD_WOOD = 'ADD_WOOD';

export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL';

export const GET_SITE_DATA = 'GET_SITE_DATA';
export const UPDATE_SITE_DATA = 'UPDATE_SITE_DATA';
